image: awhalen/docker-php-composer-node

before_script:
  - composer install
  - npm install

cache:
  paths:
    - node_modules/
    - vendor/

pages:
  script:
    - npm run deploy
    - mv build_production/ public/
  artifacts:
    paths:
      - public
  only:
    - master
