image: composer

before_script:
  - dnf install nodejs node npm
  - npm install
  - composer install

cache:
  paths:
    - node_modules/
    - vendor/

pages:
  script:
    - npm run deploy
    - mv build_production/ public/
  artifacts:
    paths:
      - public
  only:
    - master
